version: '2'
services:
  database:
    image: postgres:9.5
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_DB=polls_db
  redis:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"
